// flow-typed signature: c1563ee837aaa35dea20310141b09465
// flow-typed version: <<STUB>>/webpack-init_v^0.1.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-init'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-init' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-init/bin/webpack-init' {
  declare module.exports: any;
}

declare module 'webpack-init/lib/handleAnswers' {
  declare module.exports: any;
}

declare module 'webpack-init/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-init/lib/installModules' {
  declare module.exports: any;
}

declare module 'webpack-init/lib/loaderConfig' {
  declare module.exports: any;
}

declare module 'webpack-init/lib/promptInputs' {
  declare module.exports: any;
}

declare module 'webpack-init/src/handleAnswers' {
  declare module.exports: any;
}

declare module 'webpack-init/src/index' {
  declare module.exports: any;
}

declare module 'webpack-init/src/installModules' {
  declare module.exports: any;
}

declare module 'webpack-init/src/loaderConfig' {
  declare module.exports: any;
}

declare module 'webpack-init/src/promptInputs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-init/bin/webpack-init.js' {
  declare module.exports: $Exports<'webpack-init/bin/webpack-init'>;
}
declare module 'webpack-init/lib/handleAnswers.js' {
  declare module.exports: $Exports<'webpack-init/lib/handleAnswers'>;
}
declare module 'webpack-init/lib/index.js' {
  declare module.exports: $Exports<'webpack-init/lib/index'>;
}
declare module 'webpack-init/lib/installModules.js' {
  declare module.exports: $Exports<'webpack-init/lib/installModules'>;
}
declare module 'webpack-init/lib/loaderConfig.js' {
  declare module.exports: $Exports<'webpack-init/lib/loaderConfig'>;
}
declare module 'webpack-init/lib/promptInputs.js' {
  declare module.exports: $Exports<'webpack-init/lib/promptInputs'>;
}
declare module 'webpack-init/src/handleAnswers.js' {
  declare module.exports: $Exports<'webpack-init/src/handleAnswers'>;
}
declare module 'webpack-init/src/index.js' {
  declare module.exports: $Exports<'webpack-init/src/index'>;
}
declare module 'webpack-init/src/installModules.js' {
  declare module.exports: $Exports<'webpack-init/src/installModules'>;
}
declare module 'webpack-init/src/loaderConfig.js' {
  declare module.exports: $Exports<'webpack-init/src/loaderConfig'>;
}
declare module 'webpack-init/src/promptInputs.js' {
  declare module.exports: $Exports<'webpack-init/src/promptInputs'>;
}
